config/routes.rb
Rails.application.routes.draw do
  get 'like/_likebutton'
  get 'deepfunction/_deepfunctionform'
  get 'comment/_commentsform'
  get 'function/_functionform'
  get 'design/_designform'
  root 'welcome#home'

  get 'welcome/home'
  get 'welcome/off_discussion'
  get 'welcome/agendas'
  get 'welcome/meetings'
  get 'welcome/chairmen'
  get 'welcome/contributions'
  get 'welcome/calendar'
  get 'welcome/events'
  get 'welcome/about'
  get 'welcome/rel_media'
  get 'welcome/financials'
  get 'welcome/votes'
  get 'welcome/debate'
  get 'welcome/donations'
  get 'welcome/developments'
  get 'welcome/miss_statement'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/deepfunction.rb
class Deepfunction < ApplicationRecord
end

app/models/design.rb
class Design < ApplicationRecord
end

app/models/function.rb
class Function < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def _commentsform
  end
end

app/controllers/deepfunction_controller.rb
class DeepfunctionController < ApplicationController
  def _deepfunctionform
  end
end

app/controllers/design_controller.rb
class DesignController < ApplicationController
  def _designform
  end
end

app/controllers/function_controller.rb
class FunctionController < ApplicationController
  def _functionform
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def _likebutton
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def off_discussion
  end

  def agendas
  end

  def meetings
  end

  def chairmen
  end

  def contributions
  end

  def calendar
  end

  def events
  end

  def about
  end

  def rel_media
  end

  def financials
  end

  def votes
  end

  def debate
  end

  def donations
  end

  def developments
  end

  def miss_statement
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/deepfunction_helper.rb
module DeepfunctionHelper
end

app/helpers/design_helper.rb
module DesignHelper
end

app/helpers/function_helper.rb
module FunctionHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/_commentsform.html.erb
<h1>Comment#_commentsform</h1>
<p>Find me in app/views/comment/_commentsform.html.erb</p>

app/views/deepfunction/_deepfunctionform.html.erb
<h1>Deepfunction#_deepfunctionform</h1>
<p>Find me in app/views/deepfunction/_deepfunctionform.html.erb</p>

app/views/design/_designform.html.erb
<h1>Design#_designform</h1>
<p>Find me in app/views/design/_designform.html.erb</p>

app/views/function/_functionform.html.erb
<h1>Function#_functionform</h1>
<p>Find me in app/views/function/_functionform.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MagneticdipoleforSS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/like/_likebutton.html.erb
<h1>Like#_likebutton</h1>
<p>Find me in app/views/like/_likebutton.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/agendas.html.erb
<h1>Welcome#agendas</h1>
<p>Find me in app/views/welcome/agendas.html.erb</p>

app/views/welcome/calendar.html.erb
<h1>Welcome#calendar</h1>
<p>Find me in app/views/welcome/calendar.html.erb</p>

app/views/welcome/chairmen.html.erb
<h1>Welcome#chairmen</h1>
<p>Find me in app/views/welcome/chairmen.html.erb</p>

app/views/welcome/debate.html.erb
<h1>Welcome#debate</h1>
<p>Find me in app/views/welcome/debate.html.erb</p>

app/views/welcome/developments.html.erb
<h1>Welcome#developments</h1>
<p>Find me in app/views/welcome/developments.html.erb</p>

app/views/welcome/donations.html.erb
<h1>Welcome#donations</h1>
<p>Find me in app/views/welcome/donations.html.erb</p>

app/views/welcome/financials.html.erb
<h1>Welcome#financials</h1>
<p>Find me in app/views/welcome/financials.html.erb</p>

app/views/welcome/home.html.erb
<h3>
<%=  link_to "About", welcome_about_path %>
<br>
<%=  link_to "Agendas", welcome_agendas_path %>
<br>
<%=  link_to "Calendar", welcome_calendar_path %>
<br>
<%=  link_to "Chairmen", welcome_chairmen_path %>
<br>
<%=  link_to "Contributions", welcome_contributions_path %>
<br>
<%=  link_to "Debate", welcome_debate_path %>
<br>
<%=  link_to "Developments", welcome_developments_path %>
<br>
<%=  link_to "Donations", welcome_donations_path %>
<br>
<%=  link_to "Events", welcome_events_path %>
<br>
<%=  link_to "Financials", welcome_financials_path %>
<br>
<%=  link_to "Home", welcome_home_path %>
<br>
<%=  link_to "Meetings", welcome_meetings_path %>
<br>
<%=  link_to "Mission Statement", welcome_miss_statement_path %>
<br>
<%=  link_to "Official Discussion", welcome_off_discussion_path %>
<br>
<%=  link_to "Related Media", welcome_rel_media_path %>
<br>
<%=  link_to "Votes", welcome_votes_path %>
</h3>

<h4></h4>




<h2>Want to contribute?</h2>
<p>
Donate or comment for suggested updates to this site's design (CSS/styles)
<br>
Donate or comment for suggested updates to this site's function. (eg. add a scrolling marquee of current news)
<br>
Donate or comment for suggested deep function updates to this site (eg. create users/forums)
<br>
Contribute on <%=  link_to "Github", "https://github.com/vedabrat/magneticdipoleforSS" %>! (Fork and pull; RoR, JavaScript, CSS, etc. friendly)
</p>

app/views/welcome/meetings.html.erb
<h1>Welcome#meetings</h1>
<p>Find me in app/views/welcome/meetings.html.erb</p>

app/views/welcome/miss_statement.html.erb
<h1>Welcome#miss_statement</h1>
<p>Find me in app/views/welcome/miss_statement.html.erb</p>

app/views/welcome/off_discussion.html.erb
<h1>Welcome#off_discussion</h1>
<p>Find me in app/views/welcome/off_discussion.html.erb</p>

app/views/welcome/rel_media.html.erb
<h1>Welcome#rel_media</h1>
<p>Find me in app/views/welcome/rel_media.html.erb</p>

app/views/welcome/votes.html.erb
<h1>Welcome#votes</h1>
<p>Find me in app/views/welcome/votes.html.erb</p>